backend/models/PelanggaranMahasiswa.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "pelanggaran_mahasiswa".
 *
 * @property int $id_pelanggaran
 * @property int $id_user
 * @property string $nim
 * @property int $id_daftarpelanggaran
 * @property int $id_dosen
 * @property string $kelas
 * @property string $nama_mahasiswa
 * @property string $deskripsi
 * @property int $id_jenis_pelanggaran
 * @property string $status
 * @property string $tanggal_pelanggaran
 *
 * @property Mahasiswa $nim0
 * @property DaftarPelanggaran $daftarpelanggaran
 * @property Dosen $dosen
 * @property JenisPelanggaran $jenisPelanggaran
 * @property SiakUser $user
 */
class PelanggaranMahasiswa extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelanggaran_mahasiswa';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'nim', 'id_daftarpelanggaran', 'id_dosen', 'kelas', 'nama_mahasiswa', 'deskripsi', 'id_jenis_pelanggaran', 'tanggal_pelanggaran'], 'required'],
            [['id_user', 'id_daftarpelanggaran', 'id_dosen', 'id_jenis_pelanggaran'], 'integer'],
            [['deskripsi'], 'string'],
            [['kelas', 'nama_mahasiswa', 'nim'], 'string', 'max' => 255],
            [['status'], 'string', 'max' => 16],
            [['tanggal_pelanggaran'], 'string', 'max' => 20],
            [['nim'], 'exist', 'skipOnError' => true, 'targetClass' => Mahasiswa::className(), 'targetAttribute' => ['nim' => 'nim']],
            [['id_daftarpelanggaran'], 'exist', 'skipOnError' => true, 'targetClass' => DaftarPelanggaran::className(), 'targetAttribute' => ['id_daftarpelanggaran' => 'id_pelanggaran']],
            [['id_dosen'], 'exist', 'skipOnError' => true, 'targetClass' => Dosen::className(), 'targetAttribute' => ['id_dosen' => 'id_dosen']],
            [['id_jenis_pelanggaran'], 'exist', 'skipOnError' => true, 'targetClass' => JenisPelanggaran::className(), 'targetAttribute' => ['id_jenis_pelanggaran' => 'id_jenis_pelanggaran']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => SiakUser::className(), 'targetAttribute' => ['id_user' => 'id_user']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_pelanggaran' => 'Id Pelanggaran',
            'id_user' => 'Petugas',
            'nim' => 'Nim',
            'id_daftarpelanggaran' => 'Pelanggaran',
            'id_dosen' => 'Dosen',
            'kelas' => 'Kelas',
            'nama_mahasiswa' => 'Nama Mahasiswa',
            'deskripsi' => 'Deskripsi',
            'id_jenis_pelanggaran' => 'Id Jenis Pelanggaran',
            'status' => 'Status',
            'tanggal_pelanggaran' => 'Tanggal Pelanggaran',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNim0()
    {
        return $this->hasOne(Mahasiswa::className(), ['nim' => 'nim']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDaftarpelanggaran()
    {
        return $this->hasOne(DaftarPelanggaran::className(), ['id_pelanggaran' => 'id_daftarpelanggaran']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDosen()
    {
        return $this->hasOne(Dosen::className(), ['id_dosen' => 'id_dosen']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisPelanggaran()
    {
        return $this->hasOne(JenisPelanggaran::className(), ['id_jenis_pelanggaran' => 'id_jenis_pelanggaran']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(SiakUser::className(), ['id_user' => 'id_user']);
    }

    public function getMahasiswa()
    {
        return $this->hasOne(Mahasiswa::className(), ['nim' => 'nim']);
    }
}

backend/controllers/PelanggaranMahasiswaController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\PelanggaranMahasiswa;
use backend\models\PelanggaranMahasiswaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\Mahasiswa;
use backend\models\Dosen;
use backend\models\DaftarPelanggaran;
use backend\models\Security;
use yii\data\ActiveDataProvider;
use backend\models\BidKeasramaan;
use backend\models\BidAkademik;
use yii\helpers\Json;

/**
 * PelanggaranMahasiswaController implements the CRUD actions for PelanggaranMahasiswa model.
 */
class PelanggaranMahasiswaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PelanggaranMahasiswa models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PelanggaranMahasiswaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAkademik()
    {
        $searchModel = new PelanggaranMahasiswaSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider1 = $searchModel->searchakademik('Not Approve');

        return $this->render('indexAkademik', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dataProvider1' => $dataProvider1,
        ]);
    }


    public function actionDosen()
    {
        $searchModel = new PelanggaranMahasiswaSearch();
        $user = Yii::$app->user->id; $dosen = Dosen::find()->where(['id_user' => $user])->one(); $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider1 = $searchModel->searchdosen($dosen['id_dosen']);

        return $this->render('indexDosen', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dataProvider1' => $dataProvider1,
        ]);
    }

    public function actionApprove($id) {
        $model = $this->findModel($id);
        $mahasiswa = Mahasiswa::find()->where(['nim' => $model->nim])->one();
        $pelanggaran = DaftarPelanggaran::find()->where(['id_pelanggaran' => $model->id_daftarpelanggaran])->one();

        $poin_sisa = $mahasiswa['poin_pelanggaran'] - $pelanggaran['poin_pelanggaran'];
        $mahasiswa->poin_pelanggaran = $poin_sisa;
        $model->status = "Approve";
        $model->save(false);
        $mahasiswa->save(false);

        $searchModel = new PelanggaranMahasiswaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider1 = $searchModel->searchakademik('Not Approve');

        return $this->render('indexAkademik', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dataProvider1' => $dataProvider1,
        ]);
    }

    public function actionMahasiswa()
    {
        $searchModel = new PelanggaranMahasiswaSearch();

        $user = Yii::$app->user->id;
        $mahasiswa = Mahasiswa::find()->where(['id_user' => $user])->one();
        $pelanggaranMahasiswa = PelanggaranMahasiswa::find()->where(['nim'=>$mahasiswa['nim']]);

        $dataProvider = new ActiveDataProvider(
            [
                'query' => $pelanggaranMahasiswa,
                'pagination' =>[
                    'pageSize' => 10
                ],
            ]
        );

        return $this->render('indexMahasiswa', [
            'searchModel' => $searchModel,
            'pelanggaranMahasiswa' => $pelanggaranMahasiswa,
            'dataProvider' => $dataProvider,
        ]);

    }




    /**
     * Displays a single PelanggaranMahasiswa model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PelanggaranMahasiswa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PelanggaranMahasiswa(); 
        $user = Yii::$app->user->id;
        $dosen = Dosen::find()->where(['id_user' => $user])->one();
        $security = Security::find()->where(['id_user' => $user])->one();
        $keasramaan = BidKeasramaan::find()->where(['id_user' => $user])->one();
        $akademik = BidAkademik::find()->where(['id_user' => $user])->one();

        if($dosen['id_user'] == $user){
            $id_user = $user;
        }elseif ($security['id_user'] == $user) {
            $id_user = $user;
        }elseif ($keasramaan['id_user'] == $user) {
            $id_user = $user;
        }else{
            $id_user = $user;
        }

        if ($model->load(Yii::$app->request->post())) {
            $mahasiswa = Mahasiswa::find()->where(['nim' => $model->nim])->one();
            $pelanggaran = DaftarPelanggaran::find()->where(['id_pelanggaran' => $model->id_daftarpelanggaran])->one();

            if($pelanggaran['jenis_pelanggaran'] == 3){
                $model->id_user = $id_user;
                $model->id_dosen = $mahasiswa['id_dosen_wali'];
                $model->id_jenis_pelanggaran = $pelanggaran['jenis_pelanggaran'];
                $model->status = "Not Approve";
                $model->save();
            }else{
                $poin_sisa = $mahasiswa['poin_pelanggaran'] - $pelanggaran['poin_pelanggaran'];
                $mahasiswa->poin_pelanggaran = $poin_sisa;
                $model->id_user = $id_user;
                $model->id_dosen = $mahasiswa['id_dosen_wali'];
                $model->id_jenis_pelanggaran = $pelanggaran['jenis_pelanggaran'];
                $model->status = "Approve";
                $model->save();
                $mahasiswa->save(false);
            }
            return $this->redirect(['view', 'id' => $model->id_pelanggaran]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing PelanggaranMahasiswa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_pelanggaran]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionGetNamaMhsKelas($nimmhs){

        //mencari nim di dalam tabel mahasiswa
        $mahasiswa=Mahasiswa::find('nama_mhs', 'kelas')->where(['nim'=>$nimmhs])->one();
        echo json::encode($mahasiswa);
    }

    /**
     * Deletes an existing PelanggaranMahasiswa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PelanggaranMahasiswa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PelanggaranMahasiswa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PelanggaranMahasiswa::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/pelanggaran-mahasiswa/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use backend\models\DaftarPelanggaran;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model backend\models\PelanggaranMahasiswa */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pelanggaran-mahasiswa-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_daftarpelanggaran')->dropDownlist(
        ArrayHelper::map(DaftarPelanggaran::find()->all(),'id_pelanggaran', 'nama_pelanggaran'),
        ['prompt'=>'Pilih Pelanggaran']
        
        ) ?>

    <?= $form->field($model, 'nim')->textInput(['maxlength' => true, 'id'=> 'nimmhs']) ?>

    <?= $form->field($model, 'nama_mahasiswa')->textInput(['maxlength' => true, 'readonly'=> 'readonly']) ?>

    <?= $form->field($model, 'kelas')->textInput(['maxlength' => true, 'readonly'=> 'readonly']) ?>

    <?= $form->field($model, 'deskripsi')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'tanggal_pelanggaran')->widget(
        DatePicker::className([
        'model' => $model,
        'attribute' => 'tanggal_pelanggaran',
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'options' => ['placeholder' => 'Tanggal Pelanggaran ...'],
        'pluginOptions'=> [
            'autoclose'=> true,
            'format'=> 'yyyy-mm-dd'
            ]
        ])

    ) ?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

<?php
$script = <<< JS

//here you right all your javascript stuff
$('#nimmhs').change(function(){
    var nimmhs = $(this).val()

    $.get('index.php?r=pelanggaran-mahasiswa/get-nama-mhs-kelas',{nimmhs:nimmhs}, function(data){
        var data = $.parseJSON(data);
        //alert(data.nama_mhs);

        $('#pelanggaranmahasiswa-nama_mahasiswa').attr('value', data.nama_mhs);
        $('#pelanggaranmahasiswa-kelas').attr('value', data.kelas);
    })
    
});

JS;
$this->registerJS($script);
?>

backend/views/pelanggaran-mahasiswa/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\PelanggaranMahasiswaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pelanggaran-mahasiswa-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_pelanggaran') ?>

    <?= $form->field($model, 'id_user') ?>

    <?= $form->field($model, 'nim') ?>

    <?= $form->field($model, 'id_daftarpelanggaran') ?>

    <?= $form->field($model, 'id_dosen') ?>

    <?php // echo $form->field($model, 'kelas') ?>

    <?php // echo $form->field($model, 'nama_mahasiswa') ?>

    <?php // echo $form->field($model, 'deskripsi') ?>

    <?php // echo $form->field($model, 'id_jenis_pelanggaran') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'tanggal_pelanggaran') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pelanggaran-mahasiswa/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\PelanggaranMahasiswa */

$this->title = 'Tambah Pelanggaran Mahasiswa';
$this->params['breadcrumbs'][] = ['label' => 'Pelanggaran Mahasiswas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pelanggaran-mahasiswa-create">

   

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/pelanggaran-mahasiswa/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PelanggaranMahasiswaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pelanggaran Mahasiswa';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pelanggaran-mahasiswa-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Tambah Pelanggaran Mahasiswa', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_pelanggaran',
            [
                'attribute' => 'id_user',
                'value'=>'user.username',
            ],
            'nama_mahasiswa',
            'kelas',

            // [
            //     'attribute' => 'nim',
            //     'value'=>'mahasiswa.nama_mhs',
            // ],            
            [
                'attribute' => 'id_daftarpelanggaran',
                'value'=>'daftarpelanggaran.nama_pelanggaran',
            ],
            [
                'attribute' => 'id_dosen',
                'value'=>'dosen.nama',
            ],
            'deskripsi:ntext',
            //'id_jenis_pelanggaran',
            //'status',
            'tanggal_pelanggaran',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/pelanggaran-mahasiswa/indexAkademik.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PelanggaranMahasiswaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//Halaman untuk melakukan approval

$this->title = 'Pelanggaran Mahasiswa yang perlu di-approve';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pelanggaran-mahasiswa-index">


   
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider1,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_pelanggaran',
            'id_user',
            [
                'attribute' => 'nim',
                'value'=>'mahasiswa.nama_mhs',
            ],            
            [
                'attribute' => 'id_daftarpelanggaran',
                'value'=>'daftarpelanggaran.nama_pelanggaran',
            ],
            [
                'attribute' => 'id_dosen',
                'value'=>'dosen.nama',
            ],
            //'kelas',
            //'nama_mahasiswa',
            //'deskripsi:ntext',
            //'id_jenis_pelanggaran',
            //'status',
            'tanggal_pelanggaran',
            [
                'attribute' => 'Action',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a('Approve', ['/pelanggaran-mahasiswa/approve', 'id'=>$model->id_pelanggaran], ['class' => 'btn btn-primary']);        
                },
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/pelanggaran-mahasiswa/indexDosen.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PelanggaranMahasiswaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pelanggaran Mahasiswa';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pelanggaran-mahasiswa-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <!-- <p>
        <?= Html::a('Tambah Pelanggaran Mahasiswa', ['create'], ['class' => 'btn btn-success']) ?>
    </p> -->

    <?= GridView::widget([
        'dataProvider' => $dataProvider1,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_pelanggaran',
            [
                'attribute' => 'id_user',
                'value'=>'user.username',
            ],
            'nama_mahasiswa',
            'kelas',

            // [
            //     'attribute' => 'nim',
            //     'value'=>'mahasiswa.nama_mhs',
            // ],            
            [
                'attribute' => 'id_daftarpelanggaran',
                'value'=>'daftarpelanggaran.nama_pelanggaran',
            ],
            [
                'attribute' => 'id_dosen',
                'value'=>'dosen.nama',
            ],
            'deskripsi:ntext',
            //'id_jenis_pelanggaran',
            //'status',
            'tanggal_pelanggaran',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/pelanggaran-mahasiswa/indexMahasiswa.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PelanggaranMahasiswaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pelanggaran Mahasiswa';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pelanggaran-mahasiswa-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id_pelanggaran',
            // 'id_user',
            [
                'attribute' => 'id_user',
                'value'=>'user.username',
            ],
            'nama_mahasiswa',
            'kelas',

            // [
            //     'attribute' => 'nim',
            //     'value'=>'mahasiswa.nama_mhs',
            // ],            
            [
                'attribute' => 'id_daftarpelanggaran',
                'value'=>'daftarpelanggaran.nama_pelanggaran',
            ],
            [
                'attribute' => 'id_dosen',
                'value'=>'dosen.nama',
            ],
            'deskripsi:ntext',
            //'id_jenis_pelanggaran',
            //'status',
            'tanggal_pelanggaran',

            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/pelanggaran-mahasiswa/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\PelanggaranMahasiswa */

$this->title = 'Update Pelanggaran Mahasiswa';
$this->params['breadcrumbs'][] = ['label' => 'Pelanggaran Mahasiswas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_pelanggaran, 'url' => ['view', 'id' => $model->id_pelanggaran]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pelanggaran-mahasiswa-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/pelanggaran-mahasiswa/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\PelanggaranMahasiswa */

$this->title = $model->id_pelanggaran;
$this->params['breadcrumbs'][] = ['label' => 'Pelanggaran Mahasiswas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pelanggaran-mahasiswa-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_pelanggaran], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_pelanggaran], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_pelanggaran',
            'id_user',
            'nim',
            'id_daftarpelanggaran',
            'id_dosen',
            'kelas',
            'nama_mahasiswa',
            'deskripsi:ntext',
            'id_jenis_pelanggaran',
            'status',
            'tanggal_pelanggaran',
        ],
    ]) ?>

</div>